=== andrewoma/quokka/modules/core/main/tags/0.1.0/src/main/resources/META-INF/quokka.ws/dtd/project-0.1.dtd
<!--
   DTD for quokka project files. See http://quokka.ws/project-reference.html for more information.

   PUBLIC "quokka.ws/dtd/project-0.1"
   SYSTEM "http://quokka.ws/dtd/project-0.1"
-->

<!ELEMENT name EMPTY>
<!ATTLIST name value CDATA #REQUIRED >
<!ATTLIST name profiles CDATA #IMPLIED >

<!ELEMENT artifact ( description? | name* ) >
<!ATTLIST artifact description CDATA #IMPLIED >
<!ATTLIST artifact name NMTOKEN #IMPLIED >
<!ATTLIST artifact type NMTOKEN #IMPLIED >
<!ATTLIST artifact paths CDATA #IMPLIED >
<!ATTLIST artifact profiles CDATA #IMPLIED >

<!ELEMENT artifacts ( artifact+ ) >
<!ATTLIST artifacts group NMTOKEN #REQUIRED >
<!ATTLIST artifacts version CDATA #REQUIRED >
<!ATTLIST artifacts type NMTOKEN #IMPLIED >

<!ELEMENT boot-dependency EMPTY >
<!ATTLIST boot-dependency group NMTOKEN #REQUIRED >
<!ATTLIST boot-dependency name NMTOKEN #IMPLIED >
<!ATTLIST boot-dependency version CDATA #REQUIRED >
<!ELEMENT bootstrap ( cores | jdks | boot-dependency )* >
<!ATTLIST bootstrap profiles CDATA #IMPLIED >
<!ATTLIST bootstrap core CDATA #IMPLIED >
<!ATTLIST bootstrap file CDATA #IMPLIED >
<!ATTLIST bootstrap java-jvm-vendor CDATA #IMPLIED >
<!ATTLIST bootstrap java-vendor CDATA #IMPLIED >
<!ATTLIST bootstrap java-version CDATA #IMPLIED >
<!ATTLIST bootstrap jvm-version CDATA #IMPLIED >
<!ATTLIST bootstrap max-memory CDATA #IMPLIED >
<!ATTLIST bootstrap profiles CDATA #IMPLIED >
<!ATTLIST bootstrap spec-version CDATA #IMPLIED >

<!ELEMENT core EMPTY >
<!ATTLIST core profiles CDATA #IMPLIED >
<!ATTLIST core version CDATA #IMPLIED >

<!ELEMENT cores ( core+ ) >
<!ATTLIST cores profiles CDATA #IMPLIED >
<!ATTLIST cores version CDATA #IMPLIED >

<!ELEMENT dependency ( path-spec* ) >
<!ATTLIST dependency group NMTOKEN #REQUIRED >
<!ATTLIST dependency name NMTOKEN #IMPLIED >
<!ATTLIST dependency paths CDATA #IMPLIED >
<!ATTLIST dependency profiles CDATA #IMPLIED >
<!ATTLIST dependency type NMTOKEN #IMPLIED >
<!ATTLIST dependency version CDATA #REQUIRED >

<!ELEMENT profile EMPTY>
<!ATTLIST profile id NMTOKEN #REQUIRED >
<!ATTLIST profile description CDATA #IMPLIED >

<!ELEMENT override-core EMPTY>
<!ELEMENT dependency-set ( profile | dependency | dependency-set | override | path | plugin | override-core )* >
<!ATTLIST dependency-set group NMTOKEN #IMPLIED >
<!ATTLIST dependency-set name NMTOKEN #IMPLIED >
<!ATTLIST dependency-set version CDATA #IMPLIED >
<!ATTLIST dependency-set profiles CDATA #IMPLIED >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT jdk ( sysproperty* ) >
<!ATTLIST jdk java-jvm-vendor CDATA #IMPLIED >
<!ATTLIST jdk java-vendor CDATA #IMPLIED >
<!ATTLIST jdk java-version CDATA #IMPLIED >
<!ATTLIST jdk jvm-version CDATA #IMPLIED >
<!ATTLIST jdk max-memory CDATA #IMPLIED >
<!ATTLIST jdk profiles CDATA #IMPLIED >
<!ATTLIST jdk spec-version CDATA #IMPLIED >

<!ELEMENT jdks ( jdk+ ) >
<!ATTLIST jdks java-jvm-vendor CDATA #IMPLIED >
<!ATTLIST jdks java-vendor CDATA #IMPLIED >
<!ATTLIST jdks java-version CDATA #IMPLIED >
<!ATTLIST jdks jvm-version CDATA #IMPLIED >
<!ATTLIST jdks max-memory CDATA #IMPLIED >
<!ATTLIST jdks profiles CDATA #IMPLIED >
<!ATTLIST jdks spec-version CDATA #IMPLIED >

<!ELEMENT override EMPTY >
<!ATTLIST override group NMTOKEN #REQUIRED >
<!ATTLIST override name NMTOKEN #IMPLIED >
<!ATTLIST override profiles CDATA #IMPLIED >
<!--<!ATTLIST override scope NMTOKEN #REQUIRED >-->
<!ATTLIST override type NMTOKEN #IMPLIED >
<!ATTLIST override version CDATA #REQUIRED >
<!ATTLIST override with CDATA #REQUIRED >

<!ELEMENT path ( description? ) >
<!ATTLIST path descend-default ( true | false ) #IMPLIED >
<!ATTLIST path description CDATA #IMPLIED >
<!ATTLIST path id NMTOKEN #REQUIRED >
<!ATTLIST path mandatory-default ( true | false ) #IMPLIED >
<!ATTLIST path profiles CDATA #IMPLIED >

<!ELEMENT path-spec EMPTY >
<!ATTLIST path-spec descend ( true | false ) #IMPLIED >
<!ATTLIST path-spec from NMTOKEN #IMPLIED >
<!ATTLIST path-spec mandatory ( true | false ) #IMPLIED >
<!ATTLIST path-spec options CDATA #IMPLIED >
<!ATTLIST path-spec to NMTOKEN #IMPLIED >
<!ATTLIST path-spec profiles CDATA #IMPLIED >

<!ELEMENT plugin ( path-spec | target )* >
<!ATTLIST plugin group NMTOKEN #REQUIRED >
<!ATTLIST plugin name NMTOKEN #IMPLIED >
<!ATTLIST plugin profiles CDATA #IMPLIED >
<!ATTLIST plugin targets CDATA #IMPLIED >
<!ATTLIST plugin version CDATA #REQUIRED >
<!ATTLIST plugin use-defaults ( true | false ) #IMPLIED >

<!ELEMENT project ( description?, artifacts?, bootstrap?, dependency-set ) >
<!ATTLIST project name CDATA #IMPLIED >
<!ATTLIST project default-target CDATA #IMPLIED >

<!ELEMENT sysproperty EMPTY >
<!ATTLIST sysproperty name CDATA #REQUIRED >
<!ATTLIST sysproperty profiles CDATA #IMPLIED >
<!ATTLIST sysproperty required ( true | false ) #IMPLIED >
<!ATTLIST sysproperty value CDATA #REQUIRED >

<!ELEMENT target EMPTY >
<!ATTLIST target alias CDATA #IMPLIED >
<!ATTLIST target depends CDATA #IMPLIED >
<!ATTLIST target name CDATA #IMPLIED >
<!ATTLIST target prefix CDATA #IMPLIED >
<!ATTLIST target template CDATA #IMPLIED >
<!ATTLIST target profiles CDATA #IMPLIED >

=== andrewoma/quokka/modules/core/repo-spi/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="core.repo-spi">
    <artifacts group="quokka.core.repo-spi" version="1.0-m01-ss">
        <artifact paths="runtime"/>
    </artifacts>

    <dependency-set>
        <dependency group="quokka.core.test" version="1.0-m01-ss" paths="test-compile(junit)"/>
        <dependency group="quokka.core.util" version="1.0-m01-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap" version="1.0-m01-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap-util" version="1.0-m01-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.version" version="1.0-m01-ss" paths="compile, runtime"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile, runtime"/>

        <dependency-set group="quokka.internal.module-depset" version="1.0-m01-ss"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/version/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project>
    <description>Quokka versioning module: implements versions, ranges and unions</description>

    <artifacts group="quokka.core.version" version="0.3-ss">
        <artifact paths="runtime"/>
    </artifacts>

    <bootstrap core="[0.2.1,0.2.1]" spec-version="[1.4,1.6]"/>

    <dependency-set>
        <dependency group="apache.ant" version="1.7.1" paths="compile, runtime+"/>
        <dependency group="quokka.core.bootstrap-util" version="0.3-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.test" version="0.3-ss" paths="test-compile(junit)"/>
              
        <dependency-set group="quokka.internal.java-depset" version="0.1-ss"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/bundle/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="core.bundle">
    <artifacts group="quokka.bundle" version="0.1">
        <artifact name="core"/>
    </artifacts>

    <!--<bootstrap>-->
    <!--<cores version="1.0">-->
    <!--<core options="xerces, xercesimpl" profiles="jdk1.2, jdk1.3"/>-->
    <!--<core profiles="-jdk1.2, -jdk1.3"/>-->
    <!--</cores>-->
    <!--<jdks max-memory="1024m">-->
    <!--<jdk spec-verion="1.2" profiles="jdk1.2"/>-->
    <!--<jdk spec-verion="1.3" profiles="jdk1.3"/>-->
    <!--<jdk spec-verion="1.4" profiles="jdk1.4"/>-->
    <!--<jdk spec-verion="1.5" profiles="jdk1.5"/>-->
    <!--<jdk spec-verion="1.6" profiles="jdk1.6"/>-->
    <!--</jdks>-->
    <!--</bootstrap>-->

    <dependency-set>
        <path id="dist" description="Libraries required for the runtime distribution"/>
        <dependency group="apache.ant" version="1.7.0" paths="dist+"/>
        <dependency group="apache.ant" name="ant-launcher" version="1.7.0" paths="dist+"/>

        <!-- Libraries for the core bundle -->
        <plugin group="quokka.plugin.jarbundle" version="0.1" targets="package"/>
        <dependency group="quokka.core.main" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.metadata" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.model" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.plugin-spi" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.repo-spi" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.repo-standard" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.util" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.bootstrap" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.bootstrap-util" version="0.1" paths="jarbundle+"/>
        <dependency group="quokka.core.version" version="0.1" paths="jarbundle+"/>

        <plugin group="quokka.plugin.standard-lifecycle" version="0.1"/>

        <dependency-set group="quokka.internal.docbook-depset" version="0.1"/>
        <plugin group="quokka.plugin.xml" version="0.1">
            <target template="transform" name="docbook" prefix="docbook"/>
        </plugin>
        <plugin group="quokka.plugin.fop" version="0.1">
            <target name="docbook-pdf" template="transform" prefix="docbook-pdf" depends="docbook"/>
        </plugin>
        <plugin group="quokka.plugin.devreport" version="0.1"/>
        <plugin group="quokka.plugin.help" version="0.1"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/repo-resolver/trunk/src/test/resources/JettyPluginITest/ibuild-quokka.xml
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">
<project name="itest">
    <artifacts group="group1" version="someversion">
        <artifact  name="name1" type="jar"/>
    </artifacts>

    <dependency-set>
        <path id="plugin"/>
        <dependency group="mortbay.jetty" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jetty-naming" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jetty-management" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jetty-plus" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jsp-2.1" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jetty-annotations" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jetty-annotations" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="start" version="6.1.11" paths="plugin"/>
        <dependency group="mortbay.jetty" name="jsp-2.0" version="6.1.11" paths="plugin"/>
        <!--<plugin group="quokka.plugin.jar" version="0.1.1-ss"/>-->
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/main/branches/0.1/src/test/resources/ProjectParserTest/profiles1-quokka.xml
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">
<project name="test">
    <artifacts group="dummy.group" version="1.0-m01-ss">
        <artifact name="artifact1" paths="runtime"/>
        <artifact name="artifact2" paths="test" profiles="p1"/>
        <artifact name="artifact3" paths="compile" profiles="p2"/>
    </artifacts>

    <dependency-set>
        <profile id="p1" description="Profile 1"/>
        <profile id="p2" description="Profile 2"/>

        <path id="runtime"/>
        <path id="test" profiles="p1"/>
        <path id="compile" profiles="p2"/>

        <dependency group="apache.ant" version="1.7.0" paths="compile, runtime"/>
        <dependency group="apache.ant" name="trax" version="1.7.0" paths="compile, runtime" profiles="p1"/>
        <dependency group="apache.ant" name="junit" version="1.7.0" paths="compile, runtime" profiles="p2"/>
        <plugin group="quokka.plugin.junitplugin" version="1.0-m01-ss">
            <target name="test1" profiles="p1"/>
            <target name="test2" profiles="p2"/>
            <target name="test3"/>
        </plugin>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/main/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project>
    <artifacts group="quokka.core.main" version="0.1.1-ss">
        <artifact paths="runtime, dist"/>
    </artifacts>

    <bootstrap core="[0.1,0.1]" spec-version="[1.4,1.6]"/>

    <dependency-set>
        <path id="dist" description="Libraries required for the runtime distribution"/>
        <dependency group="apache.ant" version="1.7.0" paths="dist+"/>
        <dependency group="apache.ant" name="ant-launcher" version="1.7.0" paths="dist+"/>

        <dependency group="quokka.core.repo-spi" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.repo-standard" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.metadata" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.model" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap-util" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.version" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.plugin-spi" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.util" version="0.1" paths="compile, runtime"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile, runtime"/>
        <dependency group="apache.ant" name="ant-launcher" version="1.7.0" paths="compile, runtime"/>
        <dependency group="quokka.core.test" version="0.1" paths="test-compile(junit)"/>
        <dependency group="quokka.core.itest" version="0.1" paths="itest"/>

        <plugin group="quokka.plugin.devreport" version="0.1"/>
        <plugin group="quokka.plugin.help" version="0.1"/>
        <dependency-set group="quokka.internal.module-depset" version="0.1"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/bootstrap/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project>
    <description>Quokka bootstrapping module: allows automatic booting of different quokka versions</description>

    <artifacts group="quokka.core.bootstrap" version="0.3-ss">
        <artifact paths="runtime"/>
    </artifacts>

    <bootstrap core="[0.2.1,0.2.1]" spec-version="[1.4,1.6]"/>

    <dependency-set>
        <dependency group="apache.ant" version="1.7.1" paths="compile, runtime"/>
        <dependency group="apache.ant" name="launcher" version="1.7.1" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap-util" version="0.3-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.version" version="0.3-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.test" version="0.3-ss" paths="test-compile(junit)"/>

        <dependency-set group="quokka.internal.java-depset" version="0.1"/>
    </dependency-set>
</project>
