=== andrewoma/quokka/modules/core/main/tags/0.1.0/src/main/resources/META-INF/quokka.ws/dtd/project-0.1.dtd
<!--
   DTD for quokka project files. See http://quokka.ws/project-reference.html for more information.

   PUBLIC "quokka.ws/dtd/project-0.1"
   SYSTEM "http://quokka.ws/dtd/project-0.1"
-->

<!ELEMENT name EMPTY>
<!ATTLIST name value CDATA #REQUIRED >
<!ATTLIST name profiles CDATA #IMPLIED >

<!ELEMENT artifact ( description? | name* ) >
<!ATTLIST artifact description CDATA #IMPLIED >
<!ATTLIST artifact name NMTOKEN #IMPLIED >
<!ATTLIST artifact type NMTOKEN #IMPLIED >
<!ATTLIST artifact paths CDATA #IMPLIED >
<!ATTLIST artifact profiles CDATA #IMPLIED >

<!ELEMENT artifacts ( artifact+ ) >
<!ATTLIST artifacts group NMTOKEN #REQUIRED >
<!ATTLIST artifacts version CDATA #REQUIRED >
<!ATTLIST artifacts type NMTOKEN #IMPLIED >

<!ELEMENT boot-dependency EMPTY >
<!ATTLIST boot-dependency group NMTOKEN #REQUIRED >
<!ATTLIST boot-dependency name NMTOKEN #IMPLIED >
<!ATTLIST boot-dependency version CDATA #REQUIRED >
<!ELEMENT bootstrap ( cores | jdks | boot-dependency )* >
<!ATTLIST bootstrap profiles CDATA #IMPLIED >
<!ATTLIST bootstrap core CDATA #IMPLIED >
<!ATTLIST bootstrap file CDATA #IMPLIED >
<!ATTLIST bootstrap java-jvm-vendor CDATA #IMPLIED >
<!ATTLIST bootstrap java-vendor CDATA #IMPLIED >
<!ATTLIST bootstrap java-version CDATA #IMPLIED >
<!ATTLIST bootstrap jvm-version CDATA #IMPLIED >
<!ATTLIST bootstrap max-memory CDATA #IMPLIED >
<!ATTLIST bootstrap profiles CDATA #IMPLIED >
<!ATTLIST bootstrap spec-version CDATA #IMPLIED >

<!ELEMENT core EMPTY >
<!ATTLIST core profiles CDATA #IMPLIED >
<!ATTLIST core version CDATA #IMPLIED >

<!ELEMENT cores ( core+ ) >
<!ATTLIST cores profiles CDATA #IMPLIED >
<!ATTLIST cores version CDATA #IMPLIED >

<!ELEMENT dependency ( path-spec* ) >
<!ATTLIST dependency group NMTOKEN #REQUIRED >
<!ATTLIST dependency name NMTOKEN #IMPLIED >
<!ATTLIST dependency paths CDATA #IMPLIED >
<!ATTLIST dependency profiles CDATA #IMPLIED >
<!ATTLIST dependency type NMTOKEN #IMPLIED >
<!ATTLIST dependency version CDATA #REQUIRED >

<!ELEMENT profile EMPTY>
<!ATTLIST profile id NMTOKEN #REQUIRED >
<!ATTLIST profile description CDATA #IMPLIED >

<!ELEMENT override-core EMPTY>
<!ELEMENT dependency-set ( profile | dependency | dependency-set | override | path | plugin | override-core )* >
<!ATTLIST dependency-set group NMTOKEN #IMPLIED >
<!ATTLIST dependency-set name NMTOKEN #IMPLIED >
<!ATTLIST dependency-set version CDATA #IMPLIED >
<!ATTLIST dependency-set profiles CDATA #IMPLIED >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT jdk ( sysproperty* ) >
<!ATTLIST jdk java-jvm-vendor CDATA #IMPLIED >
<!ATTLIST jdk java-vendor CDATA #IMPLIED >
<!ATTLIST jdk java-version CDATA #IMPLIED >
<!ATTLIST jdk jvm-version CDATA #IMPLIED >
<!ATTLIST jdk max-memory CDATA #IMPLIED >
<!ATTLIST jdk profiles CDATA #IMPLIED >
<!ATTLIST jdk spec-version CDATA #IMPLIED >

<!ELEMENT jdks ( jdk+ ) >
<!ATTLIST jdks java-jvm-vendor CDATA #IMPLIED >
<!ATTLIST jdks java-vendor CDATA #IMPLIED >
<!ATTLIST jdks java-version CDATA #IMPLIED >
<!ATTLIST jdks jvm-version CDATA #IMPLIED >
<!ATTLIST jdks max-memory CDATA #IMPLIED >
<!ATTLIST jdks profiles CDATA #IMPLIED >
<!ATTLIST jdks spec-version CDATA #IMPLIED >

<!ELEMENT override EMPTY >
<!ATTLIST override group NMTOKEN #REQUIRED >
<!ATTLIST override name NMTOKEN #IMPLIED >
<!ATTLIST override profiles CDATA #IMPLIED >
<!--<!ATTLIST override scope NMTOKEN #REQUIRED >-->
<!ATTLIST override type NMTOKEN #IMPLIED >
<!ATTLIST override version CDATA #REQUIRED >
<!ATTLIST override with CDATA #REQUIRED >

<!ELEMENT path ( description? ) >
<!ATTLIST path descend-default ( true | false ) #IMPLIED >
<!ATTLIST path description CDATA #IMPLIED >
<!ATTLIST path id NMTOKEN #REQUIRED >
<!ATTLIST path mandatory-default ( true | false ) #IMPLIED >
<!ATTLIST path profiles CDATA #IMPLIED >

<!ELEMENT path-spec EMPTY >
<!ATTLIST path-spec descend ( true | false ) #IMPLIED >
<!ATTLIST path-spec from NMTOKEN #IMPLIED >
<!ATTLIST path-spec mandatory ( true | false ) #IMPLIED >
<!ATTLIST path-spec options CDATA #IMPLIED >
<!ATTLIST path-spec to NMTOKEN #IMPLIED >
<!ATTLIST path-spec profiles CDATA #IMPLIED >

<!ELEMENT plugin ( path-spec | target )* >
<!ATTLIST plugin group NMTOKEN #REQUIRED >
<!ATTLIST plugin name NMTOKEN #IMPLIED >
<!ATTLIST plugin profiles CDATA #IMPLIED >
<!ATTLIST plugin targets CDATA #IMPLIED >
<!ATTLIST plugin version CDATA #REQUIRED >
<!ATTLIST plugin use-defaults ( true | false ) #IMPLIED >

<!ELEMENT project ( description?, artifacts?, bootstrap?, dependency-set ) >
<!ATTLIST project name CDATA #IMPLIED >
<!ATTLIST project default-target CDATA #IMPLIED >

<!ELEMENT sysproperty EMPTY >
<!ATTLIST sysproperty name CDATA #REQUIRED >
<!ATTLIST sysproperty profiles CDATA #IMPLIED >
<!ATTLIST sysproperty required ( true | false ) #IMPLIED >
<!ATTLIST sysproperty value CDATA #REQUIRED >

<!ELEMENT target EMPTY >
<!ATTLIST target alias CDATA #IMPLIED >
<!ATTLIST target depends CDATA #IMPLIED >
<!ATTLIST target name CDATA #IMPLIED >
<!ATTLIST target prefix CDATA #IMPLIED >
<!ATTLIST target template CDATA #IMPLIED >
<!ATTLIST target profiles CDATA #IMPLIED >

=== andrewoma/quokka/modules/internal/site/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="internal.site">
    <artifacts group="quokka.internal.site" version="1.0-m01-ss">
        <artifact/>
    </artifacts>

    <dependency-set>
        <path id="site_naut05_custom"/>

        <plugin group="quokka.plugin.resources" version="1.0-m01-ss"/>
        <plugin group="quokka.plugin.standard-lifecycle" version="1.0-m01-ss"/>
        <plugin group="quokka.plugin.jar" version="1.0-m01-ss"/>

        <dependency group="apache.ant" name="trax" version="1.7" paths="xml-transform"/>
        <dependency group="sf.saxon" version="6.5.3" paths="xml-transform"/>
        <dependency group="sf.docbook" name="saxon-xsl-ext" version="1.72" paths="xml-transform"/>

        <dependency group="quokka.xmlcat.site-naut05-custom" version="1.0-m01-ss"
                    paths="xml-catalog, site_naut05_custom"/>
        <dependency group="quokka.xmlcat.xhtml1-20020801" version="1.0-m01-ss" paths="xml-catalog"/>
        <dependency group="quokka.xmlcat.docbook-xsl-1-72-0" version="1.0-m01-ss" paths="xml-catalog"/>
        <dependency group="quokka.xmlcat.docbook-dtd-4-5" version="1.0-m01-ss" paths="xml-catalog"/>

        <dependency group="apache.ant" name="jsch" version="1.7" paths="ant-types"/>
        <dependency group="sf.jsch" version="0.1.35" paths="ant-types"/>

        <!--<dependency group="apache.commons.net" version="1.4.1" paths="ant-types"/>-->
        <!--<dependency group="apache.ant" name="commons-net" version="1.7" paths="ant-types"/>-->

        <dependency-set group="quokka.internal.docbook-depset" version="1.0-m01-ss"/>
        <plugin group="quokka.plugin.xml" version="1.0-m01-ss">
            <target name="transform-html" template="transform" prefix="transform-html"/>
            <target name="transform-temp-html" template="transform" prefix="transform-temp-html"
                    depends="quokka.help:generate-summary"/>
            <target name="transform-docbook" template="transform" prefix="transform-docbook"/>
            <target name="transform-docbook-html" template="transform" prefix="transform-docbook-html"
                    depends="transform-docbook"/>
        </plugin>
        <plugin group="quokka.plugin.help" version="1.0-m01-ss">
            <target name="generate-summary" depends="transform-html"/>
        </plugin>
        <plugin group="quokka.plugin.devreport" version="1.0-m01-ss"/>
        <plugin group="quokka.plugin.help" version="1.0-m01-ss"/>
        <plugin group="quokka.plugin.resources" version="1.0-m01-ss">
            <target name="extract-resources" template="extract" prefix="extract-resources"/>
        </plugin>

    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/model/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="core.model">
    <artifacts group="quokka.core.model" version="0.1">
        <artifact paths="runtime"/>
    </artifacts>

<!--
    <bootstrap>
        <cores>
            <core version="1.0-m01"/>
        </cores>
        <jdks java-version="">
            <jdk max-memory="512m" spec-version="1.6">
                <sysproperty name="os.arch" value="Windows" required="true"/>
            </jdk>
        </jdks>
        <boot-dependency group="asdfasf" name="sfsdfs" version="asfa"/>
    </bootstrap>
-->

    <dependency-set>
        <dependency group="quokka.core.test" version="0.1" paths="test-compile(junit)"/>
        <dependency group="quokka.core.repo-spi" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.util" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap-util" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.version" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.plugin-spi" version="0.1" paths="compile, runtime"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile, runtime"/>

        <dependency-set group="quokka.internal.module-depset" version="0.1"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/metadata/tags/0.1.1/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project>
    <artifacts group="quokka.core.metadata" version="0.1.1">
        <artifact paths="runtime"/>
    </artifacts>

    <bootstrap core="[0.1.2,0.1.2]" spec-version="[1.4,1.6]"/>

    <dependency-set>
        <dependency group="quokka.core.test" version="0.1.1" paths="test-compile(junit)"/>
        <dependency group="quokka.core.repo-spi" version="0.2" paths="compile, runtime"/>
        <dependency-set group="quokka.internal.module-depset" version="0.1.2"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/internal/master/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="internal.master">
    <description>Quokka master module for building and managing all other modules at once</description>

    <bootstrap core="[0.2.1,0.2.1]" spec-version="[1.4,1.6]"/>
    <!--<bootstrap>-->
    <!--<cores version="1.0">-->
    <!--<core options="xerces, xercesimpl" profiles="jdk1.2, jdk1.3"/>-->
    <!--<core profiles="-jdk1.2, -jdk1.3"/>-->
    <!--</cores>-->
    <!--<jdks jvm-args="-Xmx1024m">-->
    <!--<jdk spec-verion="1.2" profiles="jdk1.2"/>-->
    <!--<jdk spec-verion="1.3" profiles="jdk1.3"/>-->
    <!--<jdk spec-verion="1.4" profiles="jdk1.4"/>-->
    <!--<jdk spec-verion="1.5" profiles="jdk1.5"/>-->
    <!--<jdk spec-verion="1.6" profiles="jdk1.6"/>-->
    <!--</jdks>-->
    <!--</bootstrap>-->

    <dependency-set>
        <plugin group="quokka.plugin.standard-lifecycle" version="0.2.2"/>
        <plugin group="quokka.plugin.cobertura" version="0.2.1" use-defaults="false"
                targets="aggregate-report"/>
        <plugin group="quokka.plugin.junitreport" version="0.2.2" use-defaults="false"
                targets="aggregate-report"/>
        <plugin group="quokka.plugin.help" version="0.2.2" use-defaults="false"
                targets="aggregate-report, help"/>
        <plugin group="quokka.plugin.devreport" version="0.2.1" use-defaults="false" targets="reports"/>
        <plugin group="quokka.plugin.subversion" version="0.2.1"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/ant-optional/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project default-target="package">
    <artifacts group="quokka.core.ant-optional-1-7-0" version="1.0-ss">
        <artifact paths="jarbundle:bundle"/>
    </artifacts>

    <bootstrap core="[0.1.1,0.1.1]" spec-version="[1.4,1.6]"/>

    <dependency-set>
        <!-- Bundle all of the ANT optional jars into a single .jar file for easier management -->
        <plugin group="quokka.plugin.jarbundle" version="0.1" targets="package"/>

        <dependency group="apache.ant" version="1.7.0" name="antlr" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="apache-oro" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="apache-regexp" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="apache-resolver" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="bcel" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="bsf" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="commons-logging" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="commons-net" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="jai" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="javamail" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="jdepend" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="jmf" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="jsch" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="junit" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="log4j" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="netrexx" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="nodeps" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="starteam" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="stylebook" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="swing" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="testutil" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="trax" paths="jarbundle+"/>
        <dependency group="apache.ant" version="1.7.0" name="weblogic" paths="jarbundle+"/>

        <plugin group="quokka.plugin.standard-lifecycle" version="0.1"/>
        <plugin group="quokka.plugin.devreport" version="0.1"/>
        <plugin group="quokka.plugin.help" version="0.1.1"/>
        <plugin group="quokka.plugin.release" version="0.1"/>
        <plugin group="quokka.plugin.subversion" version="0.1"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/itest/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="core.itest">
    <artifacts group="quokka.core.itest" version="1.0-m01-ss">
        <artifact paths="runtime"/>
    </artifacts>

    <dependency-set>
        <dependency group="quokka.core.test" version="1.0-m01-ss" paths="compile(junit), runtime"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile"/>
        <dependency group="quokka.core.repo-spi" version="1.0-m01-ss" paths="compile"/>
        <dependency group="quokka.core.repo-standard" version="1.0-m01-ss" paths="compile"/>
        <dependency group="quokka.core.util" version="1.0-m01-ss" paths="compile"/>
        <dependency group="quokka.core.main" version="1.0-m01-ss" paths="compile"/>
        <dependency group="quokka.core.plugin-spi" version="1.0-m01-ss" paths="compile, runtime"/>

        <dependency-set group="quokka.internal.module-depset" version="1.0-m01-ss"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/repo-standard/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="core.repo-standard">
    <artifacts group="quokka.core.repo-standard" version="0.1">
        <artifact paths="runtime"/>
    </artifacts>

    <dependency-set>
        <dependency group="quokka.core.bootstrap" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.bootstrap-util" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.version" version="0.1" paths="compile, runtime"/>

        <dependency group="quokka.core.repo-spi" version="0.1" paths="compile, runtime"/>
        <dependency group="quokka.core.util" version="0.1" paths="compile, runtime"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile, runtime"/>
        <dependency group="quokka.core.test" version="0.1" paths="test-compile(junit)"/>
        <dependency-set group="quokka.internal.module-depset" version="0.1"/>
    </dependency-set>
</project>

=== andrewoma/quokka/modules/core/util/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-0.1" "http://quokka.ws/dtd/project-0.1.dtd">

<project name="core.util">
    <artifacts group="quokka.core.util" version="0.1">
        <artifact/>
    </artifacts>

    <dependency-set>
        <dependency group="quokka.core.bootstrap-util" version="0.1" paths="compile, runtime"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile, runtime"/>
        <dependency group="apache.ant" name="ant-launcher" version="1.7.0" paths="compile, runtime"/>

        <dependency group="quokka.core.test" version="0.1" paths="test-compile(junit)"/>
        <dependency-set group="quokka.internal.module-depset" version="0.1"/>
    </dependency-set>
</project>
