=== andrewoma/quokka/modules/core/main/trunk/src/main/resources/META-INF/quokka.ws/dtd/project-1.0-m01.dtd
<!--
   DTD for quokka project files. See http://quokka.ws/project-reference.html for more information.

   PUBLIC "quokka.ws/dtd/project-1.0-m01"
   SYSTEM "http://quokka.ws/dtd/project-1.0-m01.dtd"
-->

<!ELEMENT artifact ( description? ) >
<!ATTLIST artifact description NMTOKEN #IMPLIED >
<!ATTLIST artifact name NMTOKEN #IMPLIED >
<!ATTLIST artifact type NMTOKEN #IMPLIED >
<!ATTLIST artifact paths CDATA #IMPLIED >
<!ATTLIST artifact profiles CDATA #IMPLIED >

<!ELEMENT artifacts ( artifact+ ) >
<!ATTLIST artifacts group NMTOKEN #REQUIRED >
<!ATTLIST artifacts version NMTOKEN #REQUIRED >
<!ATTLIST artifacts type NMTOKEN #IMPLIED >

<!ELEMENT boot-dependency EMPTY >
<!ATTLIST boot-dependency group NMTOKEN #REQUIRED >
<!ATTLIST boot-dependency name NMTOKEN #IMPLIED >
<!ATTLIST boot-dependency version CDATA #REQUIRED >
<!ELEMENT bootstrap ( cores | jdks | boot-dependency )* >
<!ATTLIST bootstrap profiles NMTOKEN #IMPLIED >

<!ELEMENT core EMPTY >
<!ATTLIST core profiles CDATA #IMPLIED >
<!ATTLIST core version NMTOKEN #IMPLIED >

<!ELEMENT cores ( core+ ) >
<!ATTLIST cores profiles NMTOKEN #IMPLIED >
<!ATTLIST cores version NMTOKEN #IMPLIED >

<!ELEMENT dependency ( path-spec* ) >
<!ATTLIST dependency group NMTOKEN #REQUIRED >
<!ATTLIST dependency name NMTOKEN #IMPLIED >
<!ATTLIST dependency paths CDATA #IMPLIED >
<!ATTLIST dependency profiles NMTOKEN #IMPLIED >
<!ATTLIST dependency type NMTOKEN #IMPLIED >
<!ATTLIST dependency version NMTOKEN #REQUIRED >

<!ELEMENT profile EMPTY>
<!ATTLIST profile id NMTOKEN #REQUIRED >
<!ATTLIST profile description CDATA #IMPLIED >

<!ELEMENT dependency-set ( profile | dependency | dependency-set | override | path | plugin )* >
<!ATTLIST dependency-set group NMTOKEN #IMPLIED >
<!ATTLIST dependency-set name NMTOKEN #IMPLIED >
<!ATTLIST dependency-set version NMTOKEN #IMPLIED >
<!ATTLIST dependency-set profiles NMTOKEN #IMPLIED >

<!ELEMENT description ( #PCDATA ) >

<!ELEMENT jdk ( sysproperty* ) >
<!ATTLIST jdk java-jvm-vendor NMTOKEN #IMPLIED >
<!ATTLIST jdk java-vendor NMTOKEN #IMPLIED >
<!ATTLIST jdk java-version NMTOKEN #IMPLIED >
<!ATTLIST jdk jvm-version NMTOKEN #IMPLIED >
<!ATTLIST jdk max-memory NMTOKEN #IMPLIED >
<!ATTLIST jdk profiles NMTOKEN #IMPLIED >
<!ATTLIST jdk spec-version NMTOKEN #IMPLIED >

<!ELEMENT jdks ( jdk+ ) >
<!ATTLIST jdks java-jvm-vendor NMTOKEN #IMPLIED >
<!ATTLIST jdks java-vendor NMTOKEN #IMPLIED >
<!ATTLIST jdks java-version NMTOKEN #IMPLIED >
<!ATTLIST jdks jvm-version NMTOKEN #IMPLIED >
<!ATTLIST jdks max-memory NMTOKEN #IMPLIED >
<!ATTLIST jdks profiles NMTOKEN #IMPLIED >
<!ATTLIST jdks spec-version NMTOKEN #IMPLIED >

<!ELEMENT override EMPTY >
<!ATTLIST override group NMTOKEN #REQUIRED >
<!ATTLIST override name NMTOKEN #IMPLIED >
<!ATTLIST override profiles NMTOKEN #IMPLIED >
<!--<!ATTLIST override scope NMTOKEN #REQUIRED >-->
<!ATTLIST override type NMTOKEN #IMPLIED >
<!ATTLIST override version CDATA #REQUIRED >
<!ATTLIST override with NMTOKEN #REQUIRED >

<!ELEMENT path ( description? ) >
<!ATTLIST path descend-default NMTOKEN #IMPLIED >
<!ATTLIST path description CDATA #IMPLIED >
<!ATTLIST path id NMTOKEN #REQUIRED >
<!ATTLIST path mandatory-default NMTOKEN #IMPLIED >
<!ATTLIST path profiles NMTOKEN #IMPLIED >

<!ELEMENT path-spec EMPTY >
<!ATTLIST path-spec descend NMTOKEN #IMPLIED >
<!ATTLIST path-spec from NMTOKEN #REQUIRED >
<!ATTLIST path-spec mandatory NMTOKEN #IMPLIED >
<!ATTLIST path-spec options CDATA #IMPLIED >
<!ATTLIST path-spec to NMTOKEN #REQUIRED >
<!ATTLIST path-spec profiles NMTOKEN #IMPLIED >

<!ELEMENT plugin ( path-spec | target )* >
<!ATTLIST plugin group NMTOKEN #REQUIRED >
<!ATTLIST plugin name NMTOKEN #IMPLIED >
<!ATTLIST plugin profiles NMTOKEN #IMPLIED >
<!ATTLIST plugin targets CDATA #IMPLIED >
<!ATTLIST plugin version NMTOKEN #REQUIRED >
<!ATTLIST plugin use-defaults ( true | false ) #IMPLIED >

<!ELEMENT project ( description?, artifacts?, bootstrap?, dependency-set ) >
<!ATTLIST project name NMTOKEN #IMPLIED >
<!ATTLIST project default-target NMTOKEN #IMPLIED >

<!ELEMENT sysproperty EMPTY >
<!ATTLIST sysproperty name NMTOKEN #REQUIRED >
<!ATTLIST sysproperty profiles NMTOKEN #IMPLIED >
<!ATTLIST sysproperty required ( true | false ) #IMPLIED >
<!ATTLIST sysproperty value NMTOKEN #REQUIRED >

<!ELEMENT target EMPTY >
<!ATTLIST target alias NMTOKEN #IMPLIED >
<!ATTLIST target depends NMTOKEN #IMPLIED >
<!ATTLIST target name NMTOKEN #REQUIRED >
<!ATTLIST target prefix NMTOKEN #IMPLIED >
<!ATTLIST target template NMTOKEN #IMPLIED >
<!ATTLIST target profiles NMTOKEN #IMPLIED >

=== andrewoma/quokka/modules/core/plugin-spi/trunk/build-quokka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "quokka.ws/dtd/project-1.0-m01" "http://quokka.ws/dtd/project-1.0-m01.dtd">

<project name="core.plugin-spi">
    <artifacts group="quokka.core.plugin-spi" version="1.0-m01-ss">
        <artifact/>
    </artifacts>

    <dependency-set>
        <dependency group="quokka.core.bootstrap-util" version="1.0-m01-ss" paths="compile, runtime"/>
        <dependency group="quokka.core.version" version="1.0-m01-ss" paths="compile, runtime"/>

        <dependency group="quokka.core.test" version="1.0-m01-ss" paths="test-compile"/>
        <dependency group="junit" version="3.8.1" paths="test-compile"/>
        <dependency group="apache.ant" version="1.7.0" paths="compile"/>
        <dependency-set group="quokka.internal.module-depset" version="1.0-m01-ss"/>
    </dependency-set>
</project>
